var num1 = 3;
var num2 = 5;
var addition = num1 + num2;
console.log("Addition: ".concat(addition));
num1 = 10;
num2 = 2;
var subtraction = num1 - num2;
console.log("Subtraction: ".concat(subtraction));
num1 = 4;
num2 = 2;
var multiplication = num1 * num2;
console.log("Multiplication: ".concat(multiplication));
num1 = 16;
num2 = 2;
var dividion = num1 / num2;
console.log("Division: ".concat(dividion));
